//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Replicator.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_EASYDUPL_FORM               101
#define IDS_TAB_GENERAL                 101
#define IDS_TAB_SETTINGS                102
#define IDS_TAB_HISTORY                 103
#define IDS_HELP_URL                    104
#define IDS_ERROR_LICENSE               105
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDS_TITLE_TESTRUN               129
#define IDR_ReplicatorTYPE              130
#define IDS_LIST_NAME                   200
#define IDS_LIST_STATUS                 201
#define IDS_LIST_LAST_RUN               202
#define IDS_LIST_SCHEDULE               203
#define IDS_LIST_TASKID                 204
#define IDS_LIST_LAST_SUCCESSFUL_RUN    205
#define IDS_EDIT_MENU                   306
#define IDS_TASK_MENU                   307
#define IDS_EDIT_TASK                   308
#define IDS_UPDATE                      309
#define IDD_GENERALPAGE                 310
#define IDD_HISTORYPAGE                 312
#define IDD_NEW_TASK                    313
#define IDR_TASK_POPUP_MENU             314
#define IDD_ADVANCED_OPTIONS            315
#define IDD_FOLDER_FORMATTER            317
#define IDD_WAITING                     323
#define IDD_SETTINGS                    325
#define IDS_HP_COL_START_TIME           400
#define IDS_HP_COL_END_TIME             401
#define IDS_HP_COL_RESULT               402
#define IDC_TAB_TASK_DETAIL             1000
#define IDS_ERROR_SAME_NAME             1000
#define IDC_TAB_INNER                   1001
#define IDS_ERROR_CREATE_PROCESS        1001
#define IDC_NEW_TASK_SOURCE             1002
#define IDS_FILTER_IS_EMPTY             1002
#define IDC_NEW_TASK_DESTINATION        1003
#define IDS_FOLDER_FORMAT_IS_EMPTY      1003
#define IDS_PROMPT_CANCEL_JOB           1004
#define IDC_NEW_TASK_INCLUDE_SUB        1005
#define IDS_ERROR_SELECT_SOURCE         1005
#define IDC_NEW_TASK_ALL_FILES          1006
#define IDS_ERROR_DEVICE_NOT_CONNECTED  1006
#define IDC_NEW_TASK_INCLUSION          1007
#define IDS_ERROR_DEVICE_DISCONNECTED   1007
#define IDC_NEW_TASK_EXCLUSION          1008
#define IDS_ERROR_PORTABLE_TO_PORTABLE  1008
#define IDC_NEW_TASK_BROWSE_DEST        1010
#define IDC_NEW_TASK_NAME               1012
#define IDC_NEW_TASK_CREATE             1015
#define IDC_NEW_TASK_FILTERS_INFO       1019
#define IDC_AO_UPDATE_OPTION            1020
#define IDC_NEW_TASK_ADV_OPTIONS        1024
#define IDC_AO_FILTERS                  1025
#define IDC_AO_DESTINATION_FORMAT       1027
#define IDC_AO_DESTINATION_FORMAT_EXAMPLE 1030
#define IDC_AF_FORMAT                   1031
#define IDC_AF_FORMAT_EXAMPLE           1032
#define IDC_AF_MACROS                   1033
#define IDC_AF_INSERT                   1034
#define IDC_AO_EDIT_FORMAT              1035
#define IDC_DESTINATION_SAME_FROM_SELECT 1036
#define IDC_DESTINATION_GROUP           1037
#define IDC_ACTION_TEXT                 1038
#define IDC_DESTINATION_SAME_FROM_ROOT  1040
#define IDC_HISTORY_LIST                1041
#define IDC_EDIT_HISTORY_DAYS           1042
#define IDC_NEW_TASK_BROWSE_SOURCE      1045
#define IDC_TEST_RUN                    1046
#define IDC_TASK_NAME                   1047
#define IDC_TASK_ID                     1048
#define IDC_SOURCE_PATH                 1049
#define IDC_DEST_PATH                   1050
#define IDC_CREATED_TIME                1051
#define IDC_CONDITIONS                  1052
#define IDS_EXCEP_CREATE_INSTANCE_FAILURE 1100
#define IDS_EXCEP_DEST_FOLDER_FORMAT_EMPTY 1101
#define IDS_EXCEP_MISMATCHED_FOLDER_PATHS 1102
#define IDS_EXCEP_CREATE_BIND_OBJ_FAILURE 1103
#define IDS_EXCEP_OPEN_FOLDER_FAILURE   1104
#define IDS_EXCEP_ACCESS_PORTABLE_DEVICE_FAILURE 1105
#define IDS_EXCEPSTR_CREATE_TASK_FAILURE 1106
#define IDS_EXCEPSTR_EDIT_TASK_FAILURE  1107
#define IDS_EXCEPSTR_DELETE_TASK_FAILURE 1108
#define IDS_CHILD_FOLDER                2001
#define IDS_ALL_FILES                   2002
#define IDS_FILES_MATCHING              2003
#define IDS_FILES_NOT_MATCHING          2004
#define IDS_WARN_OVERWRITE              2005
#define IDS_DESTINATION_SAME_FROM_SELECT 2006
#define IDS_DESTINATION_SAME_FROM_ROOT  2007
#define IDS_DESTINATION_GROUP           2008
#define IDS_UPDATE_ACTION_NEWER         2100
#define IDS_UPDATE_ACTION_KEEP_BOTH     2101
#define IDS_UPDATE_ACTION_DO_NOTHING    2102
#define IDS_UPDATE_ACTION_OVERWRITE     2103
#define IDS_SYNC_ACTION_KEEP            2110
#define IDS_SYNC_ACTION_REMOVE          2111
#define IDS_DEST_FOLDER_OPTION_SAME     2112
#define IDS_DEST_FOLDER_OPTION_GROUP_BY_DATE 2113
#define IDS_TASK_RUNNING                2114
#define IDS_RESULT_FORMAT               2115
#define IDS_ABORTED                     2116
#define IDS_COMPLETED                   2117
#define IDS_NOT_VERIFIED                2118
#define IDS_MSG_ABORTED                 2119
#define IDS_MSG_FOUND                   2120
#define IDS_MSG_ADDING                  2121
#define IDS_MSG_UPDATING                2122
#define IDS_MSG_SKIPPED                 2123
#define IDS_MSG_FAILED_TO_ADD           2124
#define IDS_MSG_FAILED_TO_UPDATE        2125
#define IDS_MSG_FAILED_TO_CREATE_FOLDER 2126
#define IDS_FF_DAY                      2200
#define IDS_FF_DAY_2D                   2201
#define IDS_FF_DAY_ALT                  2202
#define IDS_FF_WEEK_SHORT               2203
#define IDS_FF_WEEK_LONG                2204
#define IDS_FF_MONTH                    2205
#define IDS_FF_MONTH_2D                 2206
#define IDS_FF_MONTH_SHORT              2207
#define IDS_FF_MONTH_LONG               2208
#define IDS_FF_YEAR_2D                  2209
#define IDS_FF_YEAR_4D                  2210
#define IDS_FF_YEAR_ALT                 2211
#define IDS_FF_WEEK_OF_YEAR             2212
#define IDS_FF_WEEK_OF_YEAR_ALT         2213
#define IDS_TIMEFORMAT_DAYS             2214
#define IDS_TIMEFORMAT_DAY              2215
#define IDS_TIMEFORMAT_HOURS            2216
#define IDS_TIMEFORMAT_HOUR             2217
#define IDS_TIMEFORMAT_MINUTES          2218
#define IDS_TIMEFORMAT_MINUTE           2219
#define IDS_TIMEFORMAT_SECONDS          2220
#define IDS_TIMEFORMAT_SECOND           2221
#define ID_TASK_DELETE                  32771
#define ID_TASK_NEW                     32772
#define ID_Menu                         32773
#define ID_TASK_RUN                     32774
#define ID_TASK_EDIT                    32778
#define ID_TASK_STOP                    32780
#define ID_TOOLS_SETTINGS               32781
#define ID_HELP_VIEWHELP                32782
#define IDS_DELETE_CONFIRMATION         57346
#define IDS_INVALID_TASKID              57347
#define IDS_STOP_CONFIRMATION           57348

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        329
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           313
#endif
#endif
