//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Replicator.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_EASYDUPL_FORM               101
#define IDS_TAB_GENERAL                 101
#define IDS_TAB_SETTINGS                102
#define IDS_TAB_HISTORY                 103
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ReplicatorTYPE              130
#define IDS_LIST_NAME                   200
#define IDS_LIST_STATUS                 201
#define IDS_LIST_LAST_RUN               202
#define IDS_LIST_SCHEDULE               203
#define IDS_LIST_TASKID                 204
#define IDS_LIST_LAST_SUCCESSFUL_RUN    205
#define IDS_EDIT_MENU                   306
#define IDS_TASK_MENU                   307
#define IDS_EDIT_TASK                   308
#define IDS_UPDATE                      309
#define IDD_GENERALPAGE                 310
#define IDD_SETTINGSPAGE                311
#define IDD_HISTORYPAGE                 312
#define IDD_NEW_TASK                    313
#define IDR_TASK_PUPUP_MENU             314
#define IDR_TASK_POPUP_MENU             314
#define IDD_ADVANCED_OPTIONS            315
#define IDD_FOLDER_FORMATTER            317
#define IDC_TAB_TASK_DETAIL             1000
#define IDS_ERROR_SAME_NAME             1000
#define IDC_TAB_INNER                   1001
#define IDS_ERROR_CREATE_PROCESS        1001
#define IDC_NEW_TASK_SOURCE             1002
#define IDS_FILTER_IS_EMPTY             1002
#define IDC_NEW_TASK_DESTINATION        1003
#define IDS_FOLDER_FORMAT_IS_EMPTY      1003
#define IDS_PROMPT_CANCEL_JOB           1004
#define IDC_NEW_TASK_INCLUDE_SUB        1005
#define IDC_NEW_TASK_ALL_FILES          1006
#define IDC_NEW_TASK_INCLUSION          1007
#define IDC_NEW_TASK_EXCLUSION          1008
#define IDC_NEW_TASK_FILTERS            1009
#define IDC_NEW_TASK_BROWSE_DEST        1010
#define IDC_NEW_TASK_ADD_SRC            1011
#define IDC_NEW_TASK_NAME               1012
#define IDC_NEW_TASK_REMOVE_SRC         1014
#define IDC_NEW_TASK_CREATE             1015
#define IDC_NEW_TASK_RUN                1016
#define IDC_NEW_TASK_SYNC               1017
#define IDC_GENERAL_INFO                1018
#define IDC_NEW_TASK_FILTERS_INFO       1019
#define IDC_AO_UPDATE_OPTION            1020
#define IDC_AO_SYNC_OPTION              1023
#define IDC_NEW_TASK_ADV_OPTIONS        1024
#define IDC_AO_FILTERS                  1025
#define IDC_AO_DESTINATION_OPTIONS      1026
#define IDC_AO_DESTINATION_FORMAT       1027
#define IDC_AO_DESTINATION_FORMAT_STATIC 1029
#define IDC_AO_DESTINATION_FORMAT_EXAMPLE 1030
#define IDC_AF_FORMAT                   1031
#define IDC_AF_FORMAT_EXAMPLE           1032
#define IDC_AF_MACROS                   1033
#define IDC_AF_INSERT                   1034
#define IDC_AO_EDIT_FORMAT              1035
#define IDC_DESTINATION_SAME_FROM_SELECT 1036
#define IDC_DESTINATION_GROUP           1037
#define IDC_ACTION_TEXT                 1038
#define IDC_DESTINATION_SAME_FROM_ROOT  1040
#define IDC_LIST1                       1041
#define IDC_HISTORY_LIST                1041
#define IDS_TASK_INFO_TEMPLATE          2000
#define IDS_CHILD_FOLDER                2001
#define IDS_ALL_FILES                   2002
#define IDS_FILES_MATCHING              2003
#define IDS_FILES_NOT_MATCHING          2004
#define IDS_WARN_OVERWRITE              2005
#define IDS_UPDATE_ACTION_NEWER         2100
#define IDS_UPDATE_ACTION_KEEP_BOTH     2101
#define IDS_UPDATE_ACTION_DO_NOTHING    2102
#define IDS_SYNC_ACTION_KEEP            2110
#define IDS_SYNC_ACTION_REMOVE          2111
#define IDS_DEST_FOLDER_OPTION_SAME     2112
#define IDS_DEST_FOLDER_OPTION_GROUP_BY_DATE 2113
#define IDS_TASK_RUNNING                2114
#define IDS_RESULT_FORMAT               2115
#define IDS_ABORTED                     2116
#define IDS_COMPLETED                   2117
#define IDS_FF_DAY                      2200
#define IDS_FF_DAY_2D                   2201
#define IDS_FF_DAY_ALT                  2202
#define IDS_FF_WEEK_SHORT               2203
#define IDS_FF_WEEK_LONG                2204
#define IDS_FF_MONTH                    2205
#define IDS_FF_MONTH_2D                 2206
#define IDS_FF_MONTH_SHORT              2207
#define IDS_FF_MONTH_LONG               2208
#define IDS_FF_YEAR_2D                  2209
#define IDS_FF_YEAR_4D                  2210
#define IDS_FF_YEAR_ALT                 2211
#define ID_TASK_DELETE                  32771
#define ID_TASK_NEW                     32772
#define ID_Menu                         32773
#define ID_TASK_RUN                     32774
#define ID_TASK_UPDATE                  32777
#define ID_TASK_EDIT                    32778
#define ID_TASK_STOP                    32780
#define IDS_DELETE_CONFIRMATION         57346
#define IDS_INVALID_TASKID              57347
#define IDS_STOP_CONFIRMATION           57348

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        323
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           313
#endif
#endif
