#pragma once

// exception what format: <exception str>|<parameter 1>|<parameter 2>|...
// exception str resource parameter replacement format {1}, {2},...

#define EXCEPSTR_CREATE_INSTANCE_FAILURE		"CREATE_INSTANCE_FAILURE"	// 1 parameter
#define EXCEPSTR_DEST_FOLDER_FORMAT_EMPTY		"DEST_FOLDER_FORMAT_EMPTY"
#define EXCEPSTR_MISMATCHED_FOLDER_PATHS		"MISMATCHED_FOLDER_PATHS"
#define EXCEPSTR_CREATE_BIND_OBJ_FAILURE		"CREATE_BIND_OBJECT_FAILEURE"
#define EXCEPSTR_OPEN_FOLDER_FAILURE			"OPEN_FOLDER_FAILURE"
#define EXCEPSTR_ACCESS_PORTABLE_DEVICE_FAILURE	"ACCESS_PORTABLE_DEVICE_FAILURE"